name: Build Windows release

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Show Flutter version
        run: flutter --version

      - name: Debug: show repo root and list files
        run: |
          echo "Working directory:"
          pwd
          echo ""
          echo "Listing root (PowerShell):"
          powershell -Command "Get-ChildItem -Force | Sort-Object Name | Format-Table Name,Length,Mode -AutoSize"
          echo ""
          echo "Listing tree (2 levels):"
          powershell -Command "Get-ChildItem -Recurse -Depth 2 -Force | Select-Object FullName | Format-Table -AutoSize"

      - name: Cache Pub packages
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\AppData\Local\Pub\Cache
          key: pub-cache-win-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            pub-cache-win-${{ runner.os }}-

      - name: Get dependencies
        run: flutter pub get

      - name: Ensure windows platform files exist
        run: flutter create --platforms=windows .

      - name: Build Windows release
        run: flutter build windows --release

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/runner/Release/
